/**
 * @file README.md Template Generator (ChRIS App)
 */

import type { ContentContext, ContentGenerator } from '../../../types.js';

function content_generate(context: ContentContext): string {
    const projectName = context.activeProject?.name || 'chris-app';
    
    return [
        '# ' + projectName,
        '',
        'This is a _ChRIS_ plugin generated by **ARGUS**.',
        '',
        '## Installation',
        '',
        '```shell',
        'pip install .',
        '```',
        '',
        '## Local Usage',
        '',
        '```shell',
        projectName + ' incoming/ outgoing/',
        '```'
    ].join('\n');
}

export const chrisReadmeGenerator: ContentGenerator = {
    pattern: 'chris-readme',
    generate: content_generate
};