/**
 * @file setup.py Template Generator
 */

import type { ContentContext, ContentGenerator } from '../../../types.js';

function content_generate(context: ContentContext): string {
    const projectName = context.activeProject?.name || 'chris-app';
    
    let out = 'from setuptools import setup\n\n';
    out += 'setup(\n';
    out += "    name='" + projectName + "',\n";
    out += "    version='1.0.0',\n";
    out += "    description='A ChRIS plugin generated by ARGUS',\n";
    out += "    author='ATLAS Developer',\n";
    out += "    author_email='dev@atlas.local',\n";
    out += "    url='https://github.com/FNNDSC/python-chrisapp-template',\n";
    out += "    py_modules=['app'],\n";
    out += "    install_requires=['chris_plugin'],\n";
    out += "    license='MIT',\n";
    out += '    entry_points={\n';
    out += "        'console_scripts': [\n";
    out += "            '" + projectName + " = app:main'\n";
    out += "        ]\n";
    out += '    },\n';
    out += '    classifiers=[\n';
    out += "        'License :: OSI Approved :: MIT License',\n";
    out += "        'Topic :: Scientific/Engineering',\n";
    out += "        'Topic :: Scientific/Engineering :: Medical Science Apps.'\n";
    out += '    ]\n';
    out += ')';
    
    return out;
}

export const chrisSetupGenerator: ContentGenerator = {
    pattern: 'chris-setup-py',
    generate: content_generate
};