/**
 * @file app.py Template Generator (ChRIS App)
 * 
 * Based on https://github.com/FNNDSC/python-chrisapp-template
 */

import type { ContentContext, ContentGenerator } from '../../../types.js';

function content_generate(context: ContentContext): string {
    const projectName = context.activeProject?.name || 'my-app';
    
    return [
        '#!/usr/bin/env python',
        '',
        'from pathlib import Path',
        'from argparse import ArgumentParser, Namespace, ArgumentDefaultsHelpFormatter',
        '',
        'from chris_plugin import chris_plugin, PathMapper',
        '',
        "__version__ = '1.0.0'",
        '',
        'DISPLAY_TITLE = r"""',
        'ChRIS App: ' + projectName.toUpperCase(),
        '"""',
        '',
        "parser = ArgumentParser(description='A ChRIS plugin generated by ARGUS.',",
        '                        formatter_class=ArgumentDefaultsHelpFormatter)',
        "parser.add_argument('-p', '--pattern', default='**/*', type=str,",
        "                    help='input file filter glob')",
        "parser.add_argument('-V', '--version', action='version',",
        "                    version=f'%(prog)s {__version__}')",
        '',
        '@chris_plugin(',
        '    parser=parser,',
        "    title='" + projectName + "',",
        "    category='Medical Imaging',",
        "    min_memory_limit='100Mi',",
        "    min_cpu_limit='1000m',",
        '    min_gpu_limit=0',
        ')',
        'def main(options: Namespace, inputdir: Path, outputdir: Path):',
        '    """',
        '    :param options: non-positional arguments parsed by the parser',
        '    :param inputdir: directory containing (read-only) input files',
        '    :param outputdir: directory where to write output files',
        '    """',
        '    print(DISPLAY_TITLE)',
        '',
        '    mapper = PathMapper.file_mapper(inputdir, outputdir, glob=options.pattern)',
        '    for input_file, output_file in mapper:',
        '        # TODO: Implement your processing logic here',
        '        print(f"Processing {input_file} -> {output_file}")',
        '        output_file.write_text(f"Processed content of {input_file.name}")',
        '',
        "if __name__ == '__main__':",
        '    main()'
    ].join('\n');
}

export const chrisAppGenerator: ContentGenerator = {
    pattern: 'chris-app-py',
    generate: content_generate
};