/**
 * @file app.py Template Generator (Federated ML Task)
 * 
 * A ChRIS app structure pre-configured for ATLAS Federated Learning.
 */

import type { ContentContext, ContentGenerator } from '../../../types.js';

function content_generate(context: ContentContext): string {
    const projectName = context.activeProject?.name || 'fed-ml-task';
    
    return [
        '#!/usr/bin/env python',
        '',
        'from pathlib import Path',
        'from argparse import ArgumentParser, Namespace, ArgumentDefaultsHelpFormatter',
        '',
        'from chris_plugin import chris_plugin, PathMapper',
        '# ATLAS/MERIDIAN shim will be injected here during Federalization',
        '# import meridian.federated as fl',
        '',
        "__version__ = '1.0.0'",
        '',
        'DISPLAY_TITLE = r"""',
        'ATLAS Federated Task: ' + projectName.toUpperCase(),
        '"""',
        '',
        "parser = ArgumentParser(description='A Federated Learning task generated by ARGUS.',",
        '                        formatter_class=ArgumentDefaultsHelpFormatter)',
        "parser.add_argument('-e', '--epochs', default=50, type=int,",
        "                    help='number of training epochs')",
        "parser.add_argument('-V', '--version', action='version',",
        "                    version=f'%(prog)s {__version__}')",
        '',
        '@chris_plugin(',
        '    parser=parser,',
        "    title='" + projectName + "',",
        "    category='Federated Learning',",
        "    min_memory_limit='2Gi',",
        "    min_cpu_limit='2000m',",
        '    min_gpu_limit=1',
        ')',
        'def main(options: Namespace, inputdir: Path, outputdir: Path):',
        '    """',
        '    User codes as if doing local training. ',
        '    ATLAS handles the distributed orchestration.',
        '    """',
        '    print(DISPLAY_TITLE)',
        '',
        '    # 1. Load Local Data (for dev/debugging)',
        '    # When federalized, ATLAS mounts the node-local dataset here.',
        '    print(f"Loading data from {inputdir}...")',
        '    ',
        '    # 2. Training Loop (Standard PyTorch/Tensorflow logic)',
        '    print(f"Starting training for {options.epochs} epochs...")',
        '    ',
        '    # 3. Save Model Weights',
        '    model_path = outputdir / "model.pth"',
        '    model_path.write_text("MODEL_WEIGHTS_STUB")',
        '    print(f"Model saved to {model_path}")',
        '',
        "if __name__ == '__main__':",
        '    main()'
    ].join('\n');
}

export const fedmlAppGenerator: ContentGenerator = {
    pattern: 'fedml-app-py',
    generate: content_generate
};