/**
 * @file argus.yaml Template Generator
 *
 * Generates the ~/.config/argus.yaml configuration file
 * with persona-specific defaults.
 *
 * @module
 */

import type { ContentContext, ContentGenerator } from '../../types.js';

/**
 * Generates the argus.yaml content.
 * Produces a YAML configuration with interface, federation, and telemetry settings.
 *
 * @param context - The content generation context.
 * @returns Plain-text YAML configuration.
 */
function content_generate(context: ContentContext): string {
    return `# ARGUS Configuration
# Persona: ${context.persona}
# Generated by VCS ProjectProvider

interface:
  theme: "lcars-classic"
  terminal_height: 600
  beckon_pulse: true

federation:
  default_strategy: "FedAvg"
  default_epochs: 50
  privacy:
    differential_privacy: true
    epsilon: 3.0

telemetry:
  enabled: true
  interval_ms: 1000
`;
}

/**
 * ContentGenerator for ~/.config/argus.yaml.
 */
export const argusConfigGenerator: ContentGenerator = {
    pattern: 'argus-config',
    generate: content_generate
};
