/**
 * @file config.yaml Template Generator
 *
 * Generates training configuration with epochs, learning rate,
 * aggregation strategy, and privacy settings.
 *
 * @module
 */

import type { ContentContext, ContentGenerator } from '../../types.js';

/**
 * Generates the config.yaml content.
 * Produces a YAML training configuration adapted to the current context.
 *
 * @param context - The content generation context.
 * @returns Plain-text YAML configuration.
 */
function content_generate(context: ContentContext): string {
    const datasetCount: number = context.selectedDatasets.length;
    const modality: string = datasetCount > 0
        ? (context.selectedDatasets[0].modality || 'xray')
        : 'xray';

    const modelMap: Record<string, string> = {
        'xray': 'ResNet50',
        'ct': 'DenseNet121',
        'mri': 'UNet3D',
        'pathology': 'EfficientNetB4'
    };
    const modelName: string = modelMap[modality] || 'ResNet50';

    return `# ARGUS Training Configuration
# Generated by VCS ContentRegistry

project:
  name: "${context.activeProject?.name || 'untitled'}"
  persona: "${context.persona}"

model:
  architecture: "${modelName}"
  pretrained: true
  input_size: [224, 224]

training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "cosine_annealing"

federation:
  strategy: "FedAvg"
  rounds: 50
  min_nodes: 2
  timeout_seconds: 300

privacy:
  differential_privacy: true
  epsilon: 3.0
  delta: 1.0e-5
  max_grad_norm: 1.0

data:
  cohort_path: "/data/cohort"
  dataset_count: ${datasetCount}
  modality: "${modality}"

output:
  model_path: "/home/user/results/model.pt"
  metrics_path: "/home/user/results/metrics.json"
  checkpoint_interval: 10
`;
}

/**
 * ContentGenerator for config.yaml files.
 */
export const configGenerator: ContentGenerator = {
    pattern: 'config',
    generate: content_generate
};
