/**
 * @file README.md Template Generator
 *
 * Generates project documentation listing datasets, topology,
 * privacy settings, and project metadata.
 *
 * @module
 */

import type { ContentContext, ContentGenerator } from '../../types.js';
import type { Dataset } from '../../../core/models/types.js';

/**
 * Generates the README.md content.
 * Lists selected datasets, network topology, and privacy configuration.
 *
 * @param context - The content generation context.
 * @returns Plain-text Markdown documentation.
 */
function content_generate(context: ContentContext): string {
    const projectName: string = context.activeProject?.name || 'Untitled Project';
    const projectDesc: string = context.activeProject?.description || 'A federated learning cohort definition.';

    const datasetLines: string = context.selectedDatasets.length > 0
        ? context.selectedDatasets.map(
            (ds: Dataset): string => `- **${ds.name}** (${ds.modality}, ${ds.imageCount} images, ${ds.provider})`
        ).join('\n')
        : '- No datasets selected';

    const totalImages: number = context.selectedDatasets.reduce(
        (sum: number, ds: Dataset): number => sum + ds.imageCount, 0
    );

    return `# ${projectName}

${projectDesc}

## Topology

- **Network:** Star Network
- **Aggregation:** FedAvg
- **Privacy:** Differential Privacy (epsilon=3.0)
- **Persona:** ${context.persona}

## Data Sources

${datasetLines}

**Total Images:** ${totalImages.toLocaleString()}

## Quick Start

\`\`\`bash
# Review cohort
ls data/

# Launch training
federate train.py
\`\`\`

## Generated

This file was generated by the ARGUS VCS ContentRegistry.
`;
}

/**
 * ContentGenerator for README.md files.
 */
export const readmeGenerator: ContentGenerator = {
    pattern: 'readme',
    generate: content_generate
};
