/**
 * @file requirements.txt Template Generator
 *
 * Generates Python dependency list for federated training.
 *
 * @module
 */

import type { ContentContext, ContentGenerator } from '../../types.js';

/**
 * Generates the requirements.txt content.
 * Lists Python packages required for MERIDIAN federated training.
 *
 * @param context - The content generation context.
 * @returns Plain-text pip requirements file.
 */
function content_generate(_context: ContentContext): string {
    return `# ARGUS Federated Training Dependencies
# Generated by VCS ContentRegistry

torch>=2.1.0
torchvision>=0.16.0
numpy>=1.24.0
pandas>=2.0.0
scikit-learn>=1.3.0
matplotlib>=3.7.0
pyyaml>=6.0
meridian-federated>=0.9.0
atlas-sdk>=1.4.0
cryptography>=41.0.0
`;
}

/**
 * ContentGenerator for requirements.txt files.
 */
export const requirementsGenerator: ContentGenerator = {
    pattern: 'requirements',
    generate: content_generate
};
