/**
 * @file train.py Template Generator
 *
 * Generates a Python federated training script that adapts to the
 * currently selected datasets, including dynamic imports and data paths.
 *
 * @module
 */

import type { ContentContext, ContentGenerator } from '../../types.js';
import type { Dataset } from '../../../core/models/types.js';

/**
 * Generates the train.py content.
 * Adapts dataset references, model architecture, and cohort paths
 * based on the current application context.
 *
 * @param context - The content generation context.
 * @returns Plain-text Python source code.
 */
function content_generate(context: ContentContext): string {
    const datasets: string[] = context.selectedDatasets.map(
        (ds: Dataset): string => ds.name || ds.id
    );
    const datasetList: string = datasets.length > 0
        ? datasets.map((name: string): string => `    "${name}",`).join('\n')
        : '    # No datasets selected';

    const modality: string = context.selectedDatasets.length > 0
        ? (context.selectedDatasets[0].modality || 'xray')
        : 'xray';

    const modelMap: Record<string, string> = {
        'xray': 'ResNet50',
        'ct': 'DenseNet121',
        'mri': 'UNet3D',
        'pathology': 'EfficientNetB4'
    };
    const modelName: string = modelMap[modality] || 'ResNet50';

    return `# ARGUS Federated Training Script
# Target: ${modelName} on Distributed Cohorts
# Generated by VCS ContentRegistry

import torch
import meridian.federated as fl
from atlas.models import ${modelName}

# ─── Configuration ───────────────────────────────────
COHORT_DATASETS = [
${datasetList}
]
EPOCHS = 50
LEARNING_RATE = 0.001
AGGREGATION = "FedAvg"

# ─── Training Loop ───────────────────────────────────
def train(cohort_id):
    """Execute federated training across trusted domains."""
    # Initialize local node context
    node = fl.Node(cohort_id)

    # Load Data (Secure Mount)
    dataset = node.load_dataset("./data/training")

    # Define Model
    model = ${modelName}(pretrained=True)
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

    # Federated Loop
    for round in range(EPOCHS):
        weights = model.train(dataset)
        fl.aggregate(weights, strategy=AGGREGATION)

        if round % 10 == 0:
            loss = model.evaluate(dataset)
            print(f"Round {round}: loss={loss:.4f}")

    return model.save()

if __name__ == "__main__":
    train("default-cohort")
`;
}

/**
 * ContentGenerator for train.py files.
 */
export const trainGenerator: ContentGenerator = {
    pattern: 'train',
    generate: content_generate
};
