#!/bin/bash
# Generate version.ts from package.json and git hash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

VERSION=$(node -p "require('$PROJECT_ROOT/package.json').version")
GIT_HASH=$(git rev-parse --short=6 HEAD 2>/dev/null || echo "unknown")

mkdir -p "$PROJECT_ROOT/src/generated"

cat > "$PROJECT_ROOT/src/generated/version.ts" << EOF
/**
 * @file Auto-generated version information
 *
 * DO NOT EDIT - Generated by scripts/generate-version.sh
 * Run 'npm run build' or 'make cook' to regenerate.
 */

export const VERSION = '$VERSION';
export const GIT_HASH = '$GIT_HASH';
EOF

echo "Generated version.ts: v$VERSION-$GIT_HASH"
